---
title: "Resources"
---

#  Resources 

## (blogs, sites, books, courses):
- Matthew Shotwell's slides (2011): ["Approaches and Barriers to Reproducible Practices in Biostatistics"](https://rstudio-pubs-static.s3.amazonaws.com/177032_7be0bffdc2274d679c03b7228ac7b91f.html)
- NIH Training Module: [Reproducibility through rigor and transparency](https://grants.nih.gov/reproducibility/module_1/presentation.html)
- Gandrud, Christopher. [Reproducible Research with R and R Studio](https://englianhu.files.wordpress.com/2016/01/reproducible-research-with-r-and-studio-2nd-edition.pdf), CRC Press, 2013.
- Xie, Yihui. [Dynamic Documents with R and knitr](http://static.latexstudio.net/wp-content/uploads/2014/03/DDR-Yihui-Xie-Chap1-3.pdf), Vol. 29. CRC Press, 2013.
- ROpenSci's blog post: ["Reproducible research is still a challenge"](https://ropensci.org/blog/2014/06/09/reproducibility/), by R. FitzJohn, M. Pennell, A. Zanne, W. Cornwell, June 9, 2014
- Karl Broman's class ["Tools for Reproducible Research"](http://kbroman.org/Tools4RR/) at UWisconsin-Madison. 
- "Reproducible Research" by Johns Hopkins on [Coursera](https://www.coursera.org/learn/reproducible-research) (Peng, Leek, Caffo) 
- Stodden, Victoria, Friedrich Leisch, and Roger D. Peng, eds. [Implementing reproducible research](https://www.jstatsoft.org/article/view/v061b02/v61b02.pdf), CRC Press, 2014.
- StackOverflow question ["Why should I use version control?"](https://stackoverflow.com/questions/1408450/why-should-i-use-version-control#:~:text=Version%20control%20gives%20you%20the,using%20tools.)
- Learn git on github: [link](https://try.github.io/levels/1/challenges/1)
- Reproducible research with R and RStudio: http://christophergandrud.github.io/RepResR-RStudio/
- Tools for reproducible research: https://kbroman.org/Tools4RR/
- Data privacy and security: https://dataprivacymanager.net/security-vs-privacy/
- BC-Gov framework for github https://github.com/bcgov/BC-Policy-Framework-For-GitHub
- Making slides with Xaringan package in RMarkdown: https://arm.rbind.io/slides/xaringan.html
- Data wrangling with R: https://cengel.github.io/R-data-wrangling/
- Data cleaning with R and tidyverse: https://towardsdatascience.com/data-cleaning-with-r-and-the-tidyverse-detecting-missing-values-ea23c519bc62
- Gallery of missing data visualization: https://cran.r-project.org/web/packages/naniar/vignettes/naniar-visualisation.html
- How does R handle missing values: https://stats.idre.ucla.edu/r/faq/how-does-r-handle-missing-values/
- What does research reproducibility mean? https://stm.sciencemag.org/content/8/341/341ps12
- Challenge to scientists: does your ten-year-old code still run? https://www.nature.com/articles/d41586-020-02462-7?utm_source=twitter&utm_medium=social&utm_content=organic&utm_campaign=NGMT_USG_JC01_GL_Nature#ref-CR1
- Reproducible Research and open science: https://ropensci.github.io/reproducibility-guide/sections/introduction/
